### ISSUE TITLE
Location prompt questions!

### ISSUE THREAD

**Issue by nickoneill** [lazerwalker/cortado#1]
Hi there, this looks awesome! Congrats on the release and open source!

You talk a bit about the power of prompting the user when they're near a location so I'm curious about your experience with your setup. It looks like you're fetching venues around the user with the coffee category (not starbucks!), then setting local notifications for those coordinates.

How frequently do you refetch nearby coffee shops? Local notifications for coordinates are subject to limitations for how many geofences can be active at once. What's your thinking behind managing how many of these are active at any time?

**Comment by lazerwalker** [comment]
Hi!

I'm using Apple's Visit Detection API, rather than geofences (check out the API documentation for `CLVisit` if you're not familiar with it). Instead of manually managing geofences, I just let the system tell me when the user has been at their current location for a decent period of time, and then I check if that location happens to be a coffee shop.

See:
https://github.com/lazerwalker/cortado/blob/master/Cortado/Interfaces/LocationFetcher.m#L44-L55,
https://github.com/lazerwalker/cortado/blob/master/Cortado/Interfaces/LocationDetector.m#L28-L45

**Comment by nickoneill** [comment]
Awesome, thanks for the clarification!
